"use client";

/** Tidal Field Guide — route composition for one-at-a-time heritage field notes. */
import { useState } from "react";
import { Button, Eyebrow, Heading, Icon, Image, Text } from "@/components/atoms";
import { heritageSites, type HeritageSite } from "@/lib/heritage";

export function FieldNotesPage() {
  const [selected, setSelected] = useState<HeritageSite>(heritageSites[0]);
  return <>
    <section aria-labelledby="notes-title" className="paper-grain border-b border-tide-ink/15"><div className="container py-14 sm:py-20"><Eyebrow className="mb-5">Route 03 · field notes</Eyebrow><Heading as="h1" id="notes-title" className="max-w-4xl">Open one record, then read the context around it.</Heading><Text className="mt-6 max-w-2xl">Select a Pangasinan site below. This route gives each record more room than a catalogue card, while staying inside the same three-site sample set.</Text></div></section>
    <section aria-label="Choose a field note" className="container py-10"><div className="grid gap-3 sm:grid-cols-3">{heritageSites.map((site, index) => <button aria-pressed={selected.id === site.id} className={`min-h-11 border p-4 text-left transition focus-visible:outline-none ${selected.id === site.id ? "border-tidal-teal bg-sea-glass/45" : "border-tide-ink/15 bg-white hover:border-tidal-teal"}`} key={site.id} onClick={() => setSelected(site)} type="button"><span className="text-xs font-extrabold uppercase tracking-[0.16em] text-tidal-teal">0{index + 1} · {site.location}</span><span className="mt-2 block font-display text-2xl tracking-[-0.03em]">{site.name}</span></button>)}</div></section>
    <section aria-labelledby="note-title" className="bg-mist py-12 sm:py-16"><div className="container grid gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-start lg:gap-16"><Image alt={selected.imageAlt} className="aspect-[4/3] border border-tide-ink/15" src={selected.imageSrc} /><article className="paper-grain border bg-white p-6 shadow-[0_8px_25px_rgba(16,42,54,0.07)] sm:p-8"><div className="flex flex-wrap items-center gap-x-5 gap-y-3 border-b border-tide-ink/15 pb-5"><span className="catalogue-label">{selected.category}</span><span className="inline-flex items-center gap-1.5 text-sm font-semibold text-charcoal/80"><Icon className="size-4 text-copper-sand" name="mapPin" />{selected.location}</span></div><Heading as="h2" className="mt-6 text-4xl sm:text-5xl" id="note-title">{selected.name}</Heading><Text className="mt-5">{selected.description} The field-note route turns the record into a focused reading moment: it keeps the landscape, location, and classification together without adding unrelated pages or sample content.</Text><div className="mt-7 flex flex-wrap gap-3 text-sm font-bold text-tidal-teal"><span className="inline-flex items-center gap-2 border border-tidal-teal/25 px-3 py-2"><Icon className="size-4" name="compass" />Context first</span><span className="inline-flex items-center gap-2 border border-tidal-teal/25 px-3 py-2"><Icon className="size-4" name="waves" />Landscape record</span></div><div className="mt-8"><Button href="/sites" showArrow tone="secondary">Return to site collection</Button></div></article></div></section>
  </>;
}
